# Generated by Django 3.0.4 on 2020-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_comun', models.TextField(max_length=128)),
                ('N_cientifico', models.TextField(max_length=128)),
                ('Familia', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pais', models.CharField(max_length=128)),
                ('Departamento', models.CharField(max_length=128)),
                ('Nombre', models.CharField(max_length=128)),
                ('Alias', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('Autor', models.CharField(max_length=128)),
                ('Observación', models.TextField(blank=True, null=True)),
                ('Especie', models.ManyToManyField(to='datos.Especie')),
                ('Lugar', models.ManyToManyField(to='datos.Lugar')),
            ],
        ),
    ]
