# Generated by Django 3.0.4 on 2020-03-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avistamiento',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='avistamiento',
            old_name='Especie',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='avistamiento',
            old_name='Latitud',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='avistamiento',
            old_name='Longitud',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='avistamiento',
            old_name='Lugar',
            new_name='lugar',
        ),
        migrations.RenameField(
            model_name='avistamiento',
            old_name='Observación',
            new_name='observación',
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='Familia',
            new_name='familia',
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='N_cientifico',
            new_name='n_cientifico',
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='N_comun',
            new_name='n_comun',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='Alias',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='Departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='Pais',
            new_name='pais',
        ),
    ]
