# Generated by Django 3.0.4 on 2020-03-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_auto_20200310_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avistamiento',
            name='lugar',
        ),
        migrations.AddField(
            model_name='avistamiento',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.Lugar'),
        ),
    ]
