# Generated by Django 3.0.4 on 2020-03-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_auto_20200310_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avistamiento',
            options={'ordering': ['-autor'], 'verbose_name': 'Avistamiento', 'verbose_name_plural': 'Avistamientos'},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['-n_comun'], 'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'ordering': ['-nombre'], 'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
    ]
