# Generated by Django 3.0.4 on 2020-03-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_auto_20200310_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avistamiento',
            options={'ordering': ['-pk'], 'verbose_name': 'Avistamiento', 'verbose_name_plural': 'Avistamientos'},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['-pk'], 'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'ordering': ['-pk'], 'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
    ]
